'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';

type AdminData={restaurant:any;role:string;orders:any[];products:any[]};
const money=(value:number)=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const translateAuthError=(message:string)=>{const m=(message||'').toLowerCase();if(m.includes('invalid login credentials'))return 'E-mail ou senha incorretos.';if(m.includes('email not confirmed'))return 'Seu e-mail ainda não foi confirmado.';if(m.includes('too many requests'))return 'Muitas tentativas. Aguarde um pouco e tente novamente.';return message||'Não foi possível entrar agora.'};
const presets=[
 {name:'Bistrô',primary:'#b93822',secondary:'#e7854f',bg:'#fff9f1',surface:'#ffffff',text:'#171717',muted:'#777777'},
 {name:'Premium',primary:'#171717',secondary:'#b99155',bg:'#f5f1e8',surface:'#ffffff',text:'#171717',muted:'#746b60'},
 {name:'Verde',primary:'#166534',secondary:'#84cc16',bg:'#f0fdf4',surface:'#ffffff',text:'#163020',muted:'#5d7162'},
 {name:'Oceano',primary:'#075985',secondary:'#06b6d4',bg:'#ecfeff',surface:'#ffffff',text:'#0c2533',muted:'#60727b'},
 {name:'Doce',primary:'#be185d',secondary:'#f472b6',bg:'#fdf2f8',surface:'#ffffff',text:'#3b1728',muted:'#806273'},
 {name:'Noturno',primary:'#7c3aed',secondary:'#ec4899',bg:'#111827',surface:'#1f2937',text:'#f9fafb',muted:'#9ca3af'},
];

export default function AdminPage(){
 const [tenant,setTenant]=useState('sabor-da-casa');const [token,setToken]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [data,setData]=useState<AdminData|null>(null);const [error,setError]=useState('');const [tab,setTab]=useState('Visão geral');const [loading,setLoading]=useState(false);
 useEffect(()=>{setTenant(new URLSearchParams(location.search).get('restaurant')||'sabor-da-casa');setToken(localStorage.getItem('mesaflow-token')||'');},[]);
 useEffect(()=>{if(token)load();},[token,tenant]);
 async function load(){try{setLoading(true);setData(await api(`admin?restaurant=${tenant}`,{headers:{authorization:`Bearer ${token}`}}));setError('');}catch(e:any){setError(translateAuthError(e.message));setData(null)}finally{setLoading(false)}}
 async function login(){try{setLoading(true);const result=await api('login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('mesaflow-token',result.access_token);setToken(result.access_token);setError('');}catch(e:any){setError(translateAuthError(e.message))}finally{setLoading(false)}}
 const orders=data?.orders||[];const revenue=orders.filter(o=>o.status!=='cancelado').reduce((s,o)=>s+Number(o.total),0);const tabs=['Visão geral','Pedidos','Cardápio','Aparência','Configurações'];
 if(!token||!data)return <main className="admin-login"><section><span className="eyebrow">MESAFLOW · RESTAURANT OS</span><h1>Operação simples. Marca forte.</h1><p>Pedidos, cardápio e identidade da sua loja em um só lugar.</p></section><form onSubmit={e=>{e.preventDefault();login()}}><div className="admin-mark">M</div><span className="muted-caps">ACESSO DO RESTAURANTE</span><h2>Bem-vindo de volta</h2><p>Entre para acessar seu restaurante.</p><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="button button-dark" disabled={loading}>{loading?'Entrando…':'Entrar no painel'}</button>{error?<small className="form-error">{error}</small>:null}</form></main>;
 return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="admin-mark">M</span><div><b>MesaFlow</b><small>Restaurant OS</small></div></div><div className="tenant-chip"><span>{data.restaurant.name?.[0]}</span><div><b>{data.restaurant.name}</b><small>{data.role==='owner'?'Proprietário':'Equipe'}</small></div></div><nav>{tabs.map(item=><button className={tab===item?'selected':''} key={item} onClick={()=>setTab(item)}>{item}</button>)}</nav><div className="sidebar-bottom"><a href={`/loja/${tenant}`} target="_blank">↗ Ver minha loja</a><button onClick={()=>{localStorage.removeItem('mesaflow-token');setToken('');setData(null)}}>Sair</button></div></aside><main className="admin-content"><header><div><span className="muted-caps">{data.restaurant.name}</span><h1>{tab}</h1><p>{tab==='Aparência'?'Defina a identidade visual da loja sem complicação.':'Gerencie esta área da sua operação.'}</p></div></header>{tab==='Visão geral'?<><section className="metric-grid"><Metric label="Faturamento" value={money(revenue)} detail="pedidos registrados"/><Metric label="Pedidos" value={String(orders.length)} detail="total no período"/></section><Orders orders={orders}/></>:null}{tab==='Pedidos'?<Orders orders={orders}/>:null}{tab==='Cardápio'?<Catalog products={data.products}/>:null}{tab==='Aparência'?<BrandEditor restaurant={data.restaurant} token={token} tenant={tenant} reload={load}/>:null}{tab==='Configurações'?<section className="admin-panel empty-panel"><h2>Configurações da loja</h2></section>:null}</main></div>
}
function Metric({label,value,detail}:{label:string,value:string,detail:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Orders({orders}:{orders:any[]}){return <section className="admin-panel"><div className="panel-title"><h2>Pedidos recentes</h2></div><div className="order-table">{orders.slice(0,12).map(o=><div className="order-row" key={o.id}><b>#{o.public_number}</b><span>{o.customer_name}</span><span>{o.status}</span><strong>{money(o.total)}</strong></div>)}</div></section>}
function Catalog({products}:{products:any[]}){return <section className="admin-panel"><div className="panel-title"><h2>Cardápio</h2></div><div className="menu-list">{products.map(p=><div className="menu-item" key={p.id}><span>🍴</span><div><b>{p.name}</b></div><strong>{money(p.price)}</strong></div>)}</div></section>}

function BrandEditor({restaurant,token,tenant,reload}:{restaurant:any;token:string;tenant:string;reload:()=>void}){
 const [form,setForm]=useState({...restaurant});const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);const [advanced,setAdvanced]=useState(false);const patch=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 const applyPreset=(p:any)=>setForm((f:any)=>({...f,primary_color:p.primary,secondary_color:p.secondary,background_color:p.bg,surface_color:p.surface,text_color:p.text,muted_text_color:p.muted,button_background_color:p.primary,button_text_color:'#ffffff',price_color:p.primary,category_active_background_color:p.primary,category_active_text_color:'#ffffff'}));
 async function save(){setSaving(true);setSaved(false);try{await api(`branding?restaurant=${tenant}`,{method:'PATCH',headers:{authorization:`Bearer ${token}`},body:JSON.stringify(form)});await reload();setSaved(true);}finally{setSaving(false)}}
 const previewStyle={'--brand':form.primary_color||'#b93822','--brand2':form.secondary_color||'#e7854f','--store-bg':form.background_color||'#fff9f1','--surface':form.surface_color||'#fff','--text':form.text_color||'#171717','--muted':form.muted_text_color||'#777','--radius':`${form.border_radius||20}px`,'--preview-font':form.font_family||'system-ui'} as React.CSSProperties;
 return <div className="appearance-shell"><section className="appearance-editor">
   <div className="appearance-card identity-card"><div className="section-heading"><div><span className="muted-caps">IDENTIDADE</span><h2>Marca do restaurante</h2><p>As informações principais que aparecem para o cliente.</p></div></div><div className="simple-grid"><label>Nome<input value={form.name||''} onChange={e=>patch('name',e.target.value)}/></label><label>Slogan<input value={form.tagline||''} onChange={e=>patch('tagline',e.target.value)}/></label><label className="wide">Logo <span className="field-hint">URL da imagem</span><input value={form.logo_url||''} onChange={e=>patch('logo_url',e.target.value)} placeholder="https://..."/></label><label className="wide">Imagem de capa <span className="field-hint">Opcional</span><input value={form.hero_image_url||''} onChange={e=>patch('hero_image_url',e.target.value)} placeholder="https://..."/></label></div></div>
   <div className="appearance-card"><div className="section-heading"><div><span className="muted-caps">TEMA</span><h2>Escolha um ponto de partida</h2><p>Você pode ajustar qualquer cor depois.</p></div></div><div className="theme-presets">{presets.map(p=><button key={p.name} onClick={()=>applyPreset(p)}><div className="preset-preview" style={{background:p.bg}}><i style={{background:p.primary}}/><i style={{background:p.secondary}}/><i style={{background:p.surface}}/></div><b>{p.name}</b></button>)}</div></div>
   <div className="appearance-card"><div className="section-heading"><div><span className="muted-caps">CORES ESSENCIAIS</span><h2>Paleta principal</h2><p>As seis cores que mais impactam a loja.</p></div></div><div className="essential-colors"><Color label="Principal" value={form.primary_color||'#b93822'} onChange={v=>patch('primary_color',v)}/><Color label="Secundária" value={form.secondary_color||'#e7854f'} onChange={v=>patch('secondary_color',v)}/><Color label="Fundo" value={form.background_color||'#fff9f1'} onChange={v=>patch('background_color',v)}/><Color label="Cards" value={form.surface_color||'#ffffff'} onChange={v=>patch('surface_color',v)}/><Color label="Texto" value={form.text_color||'#171717'} onChange={v=>patch('text_color',v)}/><Color label="Texto secundário" value={form.muted_text_color||'#777777'} onChange={v=>patch('muted_text_color',v)}/></div></div>
   <div className="appearance-card"><div className="section-heading"><div><span className="muted-caps">ESTILO</span><h2>Forma e personalidade</h2></div></div><div className="simple-grid"><label>Fonte<select value={form.font_family||'system-ui'} onChange={e=>patch('font_family',e.target.value)}><option value="system-ui">Sistema</option><option value="Arial, Helvetica, sans-serif">Arial</option><option value="Georgia, serif">Georgia</option><option value="'Trebuchet MS', sans-serif">Trebuchet</option></select></label><label>Hero<select value={form.hero_style||'gradient'} onChange={e=>patch('hero_style',e.target.value)}><option value="gradient">Gradiente</option><option value="image">Imagem</option><option value="minimal">Minimalista</option></select></label><label>Botões<select value={form.button_style||'solid'} onChange={e=>patch('button_style',e.target.value)}><option value="solid">Sólido</option><option value="outline">Contorno</option><option value="soft">Suave</option></select></label><label>Arredondamento <span className="range-value">{form.border_radius||20}px</span><input type="range" min="0" max="40" value={form.border_radius||20} onChange={e=>patch('border_radius',Number(e.target.value))}/></label></div></div>
   <div className="appearance-card advanced-card"><button className="advanced-toggle" onClick={()=>setAdvanced(v=>!v)}><div><span className="muted-caps">AVANÇADO</span><b>Cores detalhadas</b><small>Navbar, botões, preços, badges e estados ativos</small></div><span>{advanced?'−':'+'}</span></button>{advanced?<div className="advanced-grid"><Color label="Navbar" value={form.nav_background_color||'#ffffff'} onChange={v=>patch('nav_background_color',v)}/><Color label="Texto navbar" value={form.nav_text_color||'#171717'} onChange={v=>patch('nav_text_color',v)}/><Color label="Bordas" value={form.border_color||'#e7e7e4'} onChange={v=>patch('border_color',v)}/><Color label="Preço" value={form.price_color||form.primary_color||'#b93822'} onChange={v=>patch('price_color',v)}/><Color label="Botão" value={form.button_background_color||form.primary_color||'#171717'} onChange={v=>patch('button_background_color',v)}/><Color label="Texto do botão" value={form.button_text_color||'#ffffff'} onChange={v=>patch('button_text_color',v)}/><Color label="Badge" value={form.badge_background_color||'#eef7f1'} onChange={v=>patch('badge_background_color',v)}/><Color label="Texto badge" value={form.badge_text_color||'#24714b'} onChange={v=>patch('badge_text_color',v)}/><Color label="Texto do hero" value={form.hero_text_color||'#ffffff'} onChange={v=>patch('hero_text_color',v)}/><Color label="Categoria ativa" value={form.category_active_background_color||form.primary_color||'#171717'} onChange={v=>patch('category_active_background_color',v)}/></div>:null}</div>
   <div className="appearance-actions"><button className="button button-dark" onClick={save} disabled={saving}>{saving?'Salvando…':'Salvar aparência'}</button>{saved?<span>✓ Alterações salvas</span>:null}</div>
 </section><aside className="appearance-preview"><div className="preview-label"><span>PREVIEW</span><a href={`/loja/${tenant}`} target="_blank">Abrir loja ↗</a></div><div className={`store-mock hero-${form.hero_style||'gradient'} button-${form.button_style||'solid'}`} style={previewStyle}><div className="mock-nav"><div className="mock-brand"><span>{form.logo_url?<img src={form.logo_url} alt=""/>:(form.name||'R')[0]}</span><b>{form.name||'Sua loja'}</b></div><button>Sacola</button></div><div className="mock-hero" style={form.hero_style==='image'&&form.hero_image_url?{backgroundImage:`linear-gradient(#0006,#0006),url(${form.hero_image_url})`}:undefined}><small>● ABERTO AGORA</small><h2>{form.tagline||'Seu slogan aparece aqui.'}</h2><p>Peça direto do restaurante.</p><button>Fazer pedido</button></div><div className="mock-products"><article><div></div><small>MAIS PEDIDO</small><b>Prato especial</b><p>Descrição do produto</p><strong>R$ 29,90</strong></article><article><div></div><small>DISPONÍVEL</small><b>Outro favorito</b><p>Descrição do produto</p><strong>R$ 24,90</strong></article></div></div></aside></div>
}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="compact-color"><span>{label}</span><div><input type="color" value={value} onChange={e=>onChange(e.target.value)}/><input value={value} onChange={e=>onChange(e.target.value)}/></div></label>}
