import type { Metadata } from "next";
import "./globals.css";
import "./polish.css";
import "./admin-shortcut.css";
import "./admin-premium.css";
import "./menu-editor.css";
import "./product-images.css";
import "./settings-admin.css";
import "./payment-methods.css";
import "./onboarding.css";
import "./store-loading.css";
import "./account.css";
import "./account-mobile.css";
import "./activation-mobile-fix.css";
import "./patterns.css";
import "./palettes.css";
import "./order-actions.css";
import "./order-flow-cleanup.css";
import "./production-readiness.css";
import "./first-customer.css";
import "./whatsapp-order.css";
import "./product-ui.css";
import "./team-admin.css";
import "./confirm-dialog.css";
import "./admin-mobile-fix.css";
import "./admin-modern.css";
import "./admin-modern-sections.css";
import "./admin-nav-cleanup.css";
import "./store-modern.css";
import "./store-commerce.css";
import "./store-polish.css";
import "./store-variants.css";
import "./responsive-audit.css";
import "./appearance-preview.css";

export const metadata: Metadata = { title: "MesaFlow", description: "Plataforma white-label de pedidos para restaurantes" };
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="pt-BR"><body>{children}</body></html>}
