import { BadRequestException, Body, Controller, Delete, Get, Headers, Module, Patch, PayloadTooLargeException, Post, Query, Req, ServiceUnavailableException, UnsupportedMediaTypeException } from '@nestjs/common';
import { put } from '@vercel/blob';
import { randomUUID } from 'crypto';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DataSource } from 'typeorm';
import { AuthModule, AuthService } from '../auth/auth.module';
import { CategoryEntity, OrderEntity, OrderItemEntity, ProductEntity, RestaurantEntity } from '../database/entities';
import { categoryResponse, orderResponse, productResponse, restaurantResponse } from '../api-contract';

@Controller() class AdminController{constructor(private auth:AuthService,private db:DataSource){}
 @Get('admin') async dashboard(@Headers('authorization') h:string,@Query('restaurant') slug:string){const {restaurant,member}=await this.auth.tenant(h,slug);const [orders,products,categories]=await Promise.all([this.db.getRepository(OrderEntity).find({where:{restaurantId:restaurant.id},order:{createdAt:'DESC'},take:100}),this.db.getRepository(ProductEntity).find({where:{restaurantId:restaurant.id},order:{sortOrder:'ASC'}}),this.db.getRepository(CategoryEntity).find({where:{restaurantId:restaurant.id},order:{sortOrder:'ASC'}})]);const ids=orders.map(o=>o.id),items=ids.length?await this.db.getRepository(OrderItemEntity).createQueryBuilder('i').where('i.order_id IN (:...ids)',{ids}).getMany():[];return{restaurant:restaurantResponse(restaurant),role:member.role,orders:orders.map(o=>orderResponse(o,items.filter(i=>i.orderId===o.id))),products:products.map(p=>productResponse(p)),categories:categories.map(categoryResponse)}}
 @Patch('status') async status(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Body() b:any){const {restaurant}=await this.auth.tenant(h,slug);const allowed=['novo','confirmado','preparando','pronto','saiu_para_entrega','concluido','cancelado'];if(!allowed.includes(String(b.status)))throw new BadRequestException('Status inválido');const id=String(b.id||b.order_id||'');const result=await this.db.getRepository(OrderEntity).update({id,restaurantId:restaurant.id},{status:b.status});if(!result.affected)throw new BadRequestException('Pedido não encontrado');return{ok:true}}
 @Post('product') async createProduct(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Body() b:any){const {restaurant}=await this.auth.tenant(h,slug,['owner','manager']);if(!b.name||!b.category_id)throw new BadRequestException('Preencha nome e categoria');const categoryId=String(b.category_id),category=await this.db.getRepository(CategoryEntity).findOne({where:{id:categoryId,restaurantId:restaurant.id}});if(!category)throw new BadRequestException('Categoria inválida para este restaurante');const repo=this.db.getRepository(ProductEntity);const product=repo.create({restaurantId:restaurant.id,categoryId,slug:slugify(String(b.name))+'-'+Date.now().toString(36),name:String(b.name).trim(),description:String(b.description||''),price:String(Number(b.price||0).toFixed(2)),imageUrl:b.image_url||null,featured:Boolean(b.featured),active:b.active!==false,available:b.available!==false,sortOrder:Number(b.sort_order||0)});return{product:productResponse(await repo.save(product))}}
 @Patch('product') async updateProduct(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Body() b:any){const {restaurant}=await this.auth.tenant(h,slug,['owner','manager']);const repo=this.db.getRepository(ProductEntity),product=await repo.findOne({where:{id:String(b.id),restaurantId:restaurant.id}});if(!product)throw new BadRequestException('Produto não encontrado');if('category_id' in b){const categoryId=String(b.category_id),category=await this.db.getRepository(CategoryEntity).findOne({where:{id:categoryId,restaurantId:restaurant.id}});if(!category)throw new BadRequestException('Categoria inválida para este restaurante')}const fields:Record<string,string>={name:'name',description:'description',price:'price',category_id:'categoryId',image_url:'imageUrl',featured:'featured',active:'active',available:'available',sort_order:'sortOrder'};for(const [apiKey,entityKey] of Object.entries(fields))if(apiKey in b)(product as any)[entityKey]=apiKey==='price'?String(Number(b[apiKey]).toFixed(2)):b[apiKey];return{product:productResponse(await repo.save(product))}}
 @Delete('product') async deleteProduct(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Query('id') id:string){const {restaurant}=await this.auth.tenant(h,slug,['owner','manager']);await this.db.getRepository(ProductEntity).delete({id,restaurantId:restaurant.id});return{ok:true}}
 @Post('product-image') async productImage(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Req() req:any){const {restaurant}=await this.auth.tenant(h,slug,['owner','manager']);const token=process.env.BLOB_READ_WRITE_TOKEN;if(!token)throw new ServiceUnavailableException('Armazenamento de imagens não configurado.');const mime=String(req.headers?.['content-type']||'').split(';')[0].toLowerCase(),ext=imageExtension(mime);if(!ext)throw new UnsupportedMediaTypeException('Envie uma imagem JPEG, PNG, WebP ou GIF.');const body=await readBody(req,4*1024*1024);if(!body.length)throw new BadRequestException('Imagem vazia.');const blob=await put(`products/${restaurant.id}/${randomUUID()}.${ext}`,body,{access:'public',contentType:mime,token,addRandomSuffix:false});return{url:blob.url}}
 @Patch('settings') async settings(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Body() b:any){const {restaurant}=await this.auth.tenant(h,slug,['owner','manager']);const fields:Record<string,string>={active:'active',delivery_minutes_min:'deliveryMinutesMin',delivery_minutes_max:'deliveryMinutesMax',delivery_fee:'deliveryFee',accepts_delivery:'acceptsDelivery',accepts_pickup:'acceptsPickup',minimum_order:'minimumOrder',whatsapp:'whatsapp',address_text:'addressText',opening_hours:'openingHours',timezone:'timezone',payment_methods:'paymentMethods'};for(const [k,v] of Object.entries(fields))if(k in b)(restaurant as any)[v]=normalizeSetting(k,b[k]);return{restaurant:restaurantResponse(await this.db.getRepository(RestaurantEntity).save(restaurant))}}
 @Patch('branding') async branding(@Headers('authorization') h:string,@Query('restaurant') slug:string,@Body() b:any){const {restaurant}=await this.auth.tenant(h,slug,['owner','manager']);const fields:Record<string,string>={name:'name',tagline:'tagline',primary_color:'primaryColor',secondary_color:'secondaryColor',background_color:'backgroundColor',surface_color:'surfaceColor',text_color:'textColor',muted_text_color:'mutedTextColor',background_pattern:'backgroundPattern'};for(const [k,v] of Object.entries(fields))if(k in b)(restaurant as any)[v]=b[k];return{restaurant:restaurantResponse(await this.db.getRepository(RestaurantEntity).save(restaurant))}}
}
@Module({imports:[AuthModule,TypeOrmModule.forFeature([RestaurantEntity,OrderEntity,OrderItemEntity,ProductEntity,CategoryEntity])],controllers:[AdminController]}) export class AdminModule{}
function slugify(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'produto'}
export function imageExtension(mime:string){return({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'} as Record<string,string>)[mime]||''}
export function normalizeSetting(key:string,value:any){if(['whatsapp','address_text'].includes(key))return String(value??'').trim();if(['delivery_fee','minimum_order'].includes(key))return String(Number(value).toFixed(2));return value}
async function readBody(req:any,max:number){const declared=Number(req.headers?.['content-length']||0);if(declared>max)throw new PayloadTooLargeException('A imagem deve ter no máximo 4 MB.');const chunks:Buffer[]=[];let size=0;for await(const chunk of req){const value=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);size+=value.length;if(size>max)throw new PayloadTooLargeException('A imagem deve ter no máximo 4 MB.');chunks.push(value)}return Buffer.concat(chunks)}
